(defun dispersion-rio()
              (let (a b c)
              (print "Ingrese los valores:")
              (setq a (read))
              (setq b (read))
              (setq c (read))
              (if (AND (numberp a) (numberp b) (numberp c))
              (- (max a b c) (min a b c))
              )
             )
            )                                                                                      (defun parejo-loco-normal()
              (let (dispersion)
              (setq dispersion (dispersion-rio))
              (cond
              ((< dispersion 30) "Dia parejo")
              ((> dispersion 100) "Dia loco")
              (t "Dia normal"))))